Hotfix for https://github.com/yuzisee/pokeroo/pull/9
sh: 0: cannot open ../n_threads_minus_1.sh: No such file

diff --git a/.github/workflows/generate_db.yml b/.github/workflows/generate_db.yml
--- a/.github/workflows/generate_db.yml
+++ b/.github/workflows/generate_db.yml
@@ -3,10 +3,14 @@ name: Generate holdemdb.zip
 on:
   workflow_dispatch:
 
+# [!NOTE]
+# If the `sh n_threads_minus_1.sh 3` assertion fails, you'll want to choose a different parallelization/striping strategy to match the number of cores available
+# ↓
 # 2 3
 # 4 5 6
 # 7 8 9 10
 # 11 12 13 14 15
+# etc.
 jobs:
   rotation123:
     name: 'make db → bin/regenerate_opening_book (front rotation)'
@@ -16,7 +20,7 @@ jobs:
     - uses: actions/checkout@v5
     - name: "Build bin/regenerate_opening_book"
       run: |
-        sh ../n_threads_minus_1.sh 3 || exit 78 # EX_CONFIG
+        sh n_threads_minus_1.sh 3 || exit 78 # EX_CONFIG
         cd holdem && make db
         mkdir -vp /tmp/opening_book
     - name: "Build bin/regenerate_opening_book"
@@ -42,7 +46,7 @@ jobs:
     - uses: actions/checkout@v5
     - name: "Build bin/regenerate_opening_book"
       run: |
-        sh ../n_threads_minus_1.sh 3 || exit 78 # EX_CONFIG
+        sh n_threads_minus_1.sh 3 || exit 78 # EX_CONFIG
         cd holdem && make db
         mkdir -vp /tmp/opening_book
     - name: "Build bin/regenerate_opening_book"
